### ISSUE TITLE
handleDisconnection() called twice 

### ISSUE THREAD

**Issue by TopyrynHoper** [ItDanieru/DawnCraft_lang_Uk_Be_Ru#1]
Hi bro! I don't know what language you need to write in, but we have a problem.
I want to play with my friends on this build, and therefore, we ordered a separate hosting and threw all the mods + the map there, having previously installed the forge 1.18.2 core. But there is a problem, such an error appears in the client (Figure 1). And here is an error from the server side (Figure 2).
_________________________
Привет бро! Не знаю, на каком языке нужно писать вам, но у нас появилась одна проблема.
Я хочу поиграть с друзьями на этой сборке, а потому, заказали отдельный хостинг и все моды + карту перекинули туда, предварительно поставив ядро forge 1.18.2. Но есть незадача, появляется такая ошибка у клиента (рисунок 1). И вот ошибка со стороны сервера (рисунок 2). 

![image](https://user-images.githubusercontent.com/132920459/236851581-0c4d62e8-5eae-40bc-bde2-6671e40f4fc8.png)
(Figure 1) (рисунок 1)

![image](https://user-images.githubusercontent.com/132920459/236851409-f00b9835-caaa-4465-8c24-f5bbad575c23.png)
(Figure 2) (рисунок 2)

**Comment by ItDanieru** [comment]
Привет 
1. можешь отправить мне Лог? (log)
2. играете на Лицензионном Майнкрайте?
3. Сколько выделили Озу  на Майнкрафт?

**Comment by TopyrynHoper** [comment]
1. Лог чего именно? Сервера или клиента?
2. Никак нет
3. 12гб

**Comment by ItDanieru** [comment]
1. Сервера, но давайте я проверю ещё и Клиента.
2. Сервер настроен на то что бы запускать игроков с Пиратской версии игры?
3. а сколько Озу у вашего Компьютера?

**Comment by TopyrynHoper** [comment]
1. Окей (скинул пока чисто серверский, так как к клиентскому логу у меня нету доступа сейчас)
P.S Скину через минут 30-40
[latest.txt](https://github.com/ItDanieru/DawnCraft_lang_Uk_Be_Ru/files/11422392/latest.txt)
2. Да, настроен. (рисунок 1)
![image](https://user-images.githubusercontent.com/132920459/236861969-5b71bbb3-3409-4a57-a1fd-287cf0435bf5.png)
3. 32гб

**Comment by TopyrynHoper** [comment]
Что можете сказать?

**Comment by ItDanieru** [comment]
по логу серверу ничего сказать не могу к сожалению, друзья ваши пробовали подключаться?

**Comment by TopyrynHoper** [comment]
только 1 человек пытался подключаться, появляется у него эта ошибка (уже скидывал ранее)
сам я пока не могу подключиться, т.к. не могу скинуть файлы...

**Comment by TopyrynHoper** [comment]
Да, у меня такая же проблема высвечивается 
![image](https://user-images.githubusercontent.com/132920459/236873118-0d3bad07-609c-4850-b2be-3d2aea6b4300.png)
В логе сервера ничего не пишет
![image](https://user-images.githubusercontent.com/132920459/236873902-25f7c290-d7f9-407c-ae42-9c55997a73a6.png)

**Comment by TopyrynHoper** [comment]
Вот логи клиента, что и просили
[latest.txt](https://github.com/ItDanieru/DawnCraft_lang_Uk_Be_Ru/files/11422871/latest.txt)

**Comment by ItDanieru** [comment]
к Сожалению не могу помочь, вижу предупреждения в логах клиента на многие моды

**Comment by TopyrynHoper** [comment]
То есть, вы говорите, что есть какие то проблемы с модами в данном (в моем) клиенте?

**Comment by ItDanieru** [comment]
![image](https://user-images.githubusercontent.com/54354556/236878775-2eef5a27-2a83-47e7-83cf-48dda8b1f7b7.png)

**Comment by TopyrynHoper** [comment]
Все, понял. Сейчас попробую их исправить и скажу, получилось или нет.

**Comment by TopyrynHoper** [comment]
Проблема оказалась в ошибке двух модах, Farmers delight и nethers delight, я убрал их и ошибка была устранена.
Тикет закрыт.
Спасибо!
