### ISSUE TITLE
Перевод

### ISSUE THREAD

**Issue by Hoaper** [ItDanieru/DawnCraft_lang_Uk_Be_Ru#2]
Доброго времени суток, перевод квестов жителей вы взяли у меня. [repo](https://github.com/Hoaper/dawncraft-russian-path)
А потому, не могли бы вы указать что я тоже  участвовал в переводе.
Заранее благодарю

**Comment by ItDanieru** [comment]
Прошу прощения, но перевод Quest_Giver был написан с 0 пользователем АpmaGEEDoH.

Буду честным, по началу хотел взять ваш перевод и по этому написал вам в Issues. но из за долгого ожидания ответа уже передумал по той причине что  АpmaGEEDoH., предложил свою помощь и перевод модов.
